### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by petersoniq**

### CODE REVIEW

**Comment by vasqued2** [comment]
Thanks.  What language do I select on the front end to pull in the sk_SK.js file?  When I pick Slovenčina, the language shows as `sk`.  When I pick Slovenščina it is `sl`.  I can't find a way to get it to be `sk_SK`.  Or do I have to pick something at the browser or OS level?

**Comment by petersoniq** [comment]
Hi. Slovenčina like sk is correct.

**Comment by vasqued2** [comment]
Thanks.  So can I copy your sk_SK.js file to create a second sk.js file too?  Kind of like there is a en_US.js file and an en.js file?  They are close enough that the translations are the same.  It looks like when I select Slovenčina it is looking for a sk.js file.

**Comment by petersoniq** [comment]
Thanks tou. But I thing only sk.js will be necessary. en.js is originaly english language come from UK. It is same differences oposit to US english.

**Pull request merged**
